# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-06-21 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kiralayan',
            field=models.CharField(default=1, max_length=100, verbose_name='Kiralayan Adı:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı: '),
        ),
    ]
