# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-06-22 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20230622_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='baslama_tarih',
            field=models.CharField(default=1, max_length=100, verbose_name='Başlama Tarihi:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='bitis_tarih',
            field=models.CharField(default=1, max_length=100, verbose_name='Bitme Tarihi:'),
            preserve_default=False,
        ),
    ]
