# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-06-22 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20230622_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='baslama_tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bitis_tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
