# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-06-22 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20230622_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiralama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiralayan', models.CharField(max_length=100, verbose_name='Kiralayan Adı:')),
                ('baslama_tarih', models.DateField()),
                ('bitis_tarih', models.DateField()),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
            options={
                'ordering': ['-kiralayan', 'id'],
            },
        ),
    ]
