# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-06-22 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_kiralama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiralama',
            name='iha',
        ),
        migrations.DeleteModel(
            name='Kiralama',
        ),
    ]
